---
# eslint-disable eslint-comments/disable-enable-pair, max-lines
colors:
  background: '#161925'
  color0: '#161925'
  color1: '#282C34'
  color2: '#ED254E'
  color3: '#71F79F'
  color4: '#F9DC5C'
  color5: '#7CB7FF'
  color6: '#C74D89'
  color7: '#00C1E4'
  color8: '#DCDFE4'
  color9: '#4C5058'
  color10: '#FF4972'
  color11: '#95FFC3'
  color12: '#FFFF80'
  color13: '#A0DBFF'
  color14: '#EB71AD'
  color15: '#24E5FF'
  color16: '#FFFFFF'
config:
  gpg: https://raw.githubusercontent.com/drduh/config/master/gpg.conf
fonts:
  main: Montserrat Bold
grub:
  shiftToSee: false
  timeout: 9
removeLinuxPackages:
  - aisleriot
  - gnome-mahjongg
  - gnome-mines
  - gnome-sudoku
  - rhythmbox
removeLinuxShortcuts:
  - cmake_cmake-gui.desktop
  - display-im6.q16.desktop
  - flutter_openurl.desktop
  - htop.desktop
  - scvim.desktop
theme: Betelgeuse
softwareGroups:
  Android: &Android
    - scrcpy
  Android-Desktop: &Android-Desktop
    - android-studio
    - scrcpy-gui
  Anon: &Anon
    - onionshare
  Ansible: &Ansible
    - ansible
    - ansible-lint
    - ansibleconnect
    - awxcli
    - molecule
    - winrm-cli
  Ansible-Roles: &Ansible-Roles
    - ssh
    - swarm
    - vpn
    - wsl
    - yubikey
    - antivirus
    - common
    # - connect
    - debloat
    - defaultbrowser
    - desktop
    # - disks
    - dns
    - dnsmasq
    # - easyengine
    - environment
    - extensions
    - finish
    - firewall
    - fuse
    - guacamole
    - hosthomepage
    - hosts
    # - motd
    # - pfsense
    # - pihole
    # - pip
    - prepare
    - security
    - ssh
    # - swarm
    # - maas
  Backup: &Backup
    - autorestic
    - ghorg
    - restic
    - sanoid
  Backup-Desktop: &Backup-Desktop
    - cryptomator
    - seafile-client
    - timeshift
  Browsers: &Browsers
    - w3m
  Browsers-Desktop: &Browsers-Desktop
    - brave-browser
    - google-chrome
    - chrome-cli
    - ferdium
    - firefox
    - librewolf
    - microsoft-edge
  CI: &CI
    - act
    - argo-cli
    - drone-cli
    - fpm
    - gitlab-runner
    - glen
  CLI: &CLI
    - bash-completion
    - bandwhich
    - bat
    - bottom
    - broot
    - cheat
    - chezmoi
    - curl
    - curlie
    - delta
    - direnv
    - dog
    - dua
    - duf
    - dust
    - empty-trash
    - exa
    - fcp
    - fd
    - fkill
    - fzf
    - git
    - glances
    - glow
    - gnu
    - gping
    - gum
    - hyperfine
    - jq
    - mc
    - mcfly
    - nb
    - neovim
    - netcat
    - nmap
    - nnn
    - node
    - oh-my-posh
    - pass
    - procs
    - prettier
    - privoxy
    - recoverpy
    - ripgrep
    - ripgrep-all
    - rm-improved
    - rsync
    - sd
    - snapd
    - task
    - tmux
    - tor
    - translate
    - tree
    - vim
    - volta
    - watchexec
    - watchman
    - wget
    - whalebrew
    - wifi-password
    - yq
    - zoxide
    - zsh
    - zx
  CLI-Extras: &CLI-Extras
    - axel
    - bin
    - bitly
    - desed
    - emoj
    - fig
    - filebrowser
    - googler
    - grex
    - gron
    - hexyl
    - http-prompt
    - httpie
    - httpstat
    - imgur-uploader
    - is-up
    - jiq
    - jqp
    - litecli
    - mycli
    - nomino
    - normit
    - pastel
    - peco
    - pgcli
    - pywhat
    - slack-term
    - social-analyzer
    - speed-test
    - statcode
    - stegcloak
    - tldr
    - up
    - yank
  Cloud: &Cloud
    - awscli
    - azure-cli
    - azure-functions
    - budibase-cli
    - consul-cli
    - curator
    - doctl
    - envconsul
    - fission
    - fly
    - gcloud
    - heroku-cli
    - juju
    - lexicon
    - logcli
    - psu
    - rancher-cli
  Cloud-Storage: &Cloud-Storage
    - gdrive
    - gphotos-sync
    - rclone
    - s5cmd
  Communication-Desktop: &Communication-Desktop
    - discord
    - gitter
    - microsoft-teams
    - jitsi-meet
    - keybase
    - skype
    - slack
    - telegram
    - zoom
  Crypto: &Crypto
    - cointop
  Crypto-Desktop: &Crypto-Desktop
    - ledger-live
    - monero
    - onlykey
  DNS: &DNS
    - hostctl
    - switchhosts
  Data-Manipulation: &Data-Manipulation
    - dasel
    - fq
    - fselect
    - fx
    - gojq
    - hclq
    - htmlq
    - jo
    - jq
    - oq
    - osquery
    - pup
    - ramda
    - schema
    - xurls
    - yj
    - yq
  Database: &Database
    - sqlite
  Database-Desktop: &Database-Desktop
    - beekeeper-studio
    - sqlectron
  Development-Tools-Desktop: &Development-Tools-Desktop
    - github-desktop
    - intellij-idea-ce
    - iterm2
    - lepton
    - masscode
    - meld
    - powershell
    - redis-desktop-manager
    - visual-studio
    - xcode
  Docker: &Docker
    - bane
    - clair
    - container-structure-test
    - dive
    - docker
    - docker-slim
    - docker-pushrm
    - dockle
    - grype
    - gvisor
    - supdock
    - trivy
    - trufflehog
    - whaler
  E-mail: &E-mail
    - himalaya
  E-mail-Desktop: &E-mail-Desktop
    - mailspring
    - protonmail-import-export
    - protonmail-bridge
    - thunderbird
  Engineering-Desktop: &Engineering-Desktop
    - arduino-ide
    - cutter
    - fritzing
  Essentials: &Essentials
    - docker
  Essentials-Desktop: &Essentials-Desktop
    - firefox
    - kvantum
    - portmaster
    - rofi
    - tabby
    - vlc
    - vscode
    - vscodium
  File-System: &File-System
    # After `sudo apt-get install -y fuse libfuse-dev, the following error still shows up:
    # error: could not find system library 'fuse' required by the 'fuse' crate
    # - catfs
    - glusterfs
    - goofys
    - sshfs
  Finance: &Finance
    - infracost
  Finance-Desktop: &Finance-Desktop
    - manta
  Git: &Git
    - commitizen
    - gh
    - gist
    - git
    - git-bug
    - git-extras
    - git-filter-repo
    - git-fuzzy
    - git-lfs
    - git-open
    - git-secret
    - git-subrepo
    - gitomatic
    - git-stats
    - gitui
    - glab
    - hub
    - lazygit
    - tig
  Git-Desktop: &Git-Desktop
    - gitdock
    - gitify
    - gitkraken
  Git-Project-Tools: &Git-Project-Tools
    - appnest-readme
    - commitlint
    - git-notify
    - hbs-cli
    - husky
    - liquidjs
    - pnpm-lock-export
    - synp
    - yarnhook
  Go: &Go
    - delve
    - go
    - go-outline
    - gomodifytags
    - gopkgs
    - gopls
    - gotests
    - impl
    - staticcheck
    - wails
  Home: &Home
    - go-chromecast
  Kubernetes: &Kubernetes
    - cmctl
    - kdash
    - kn
    - kubectx
    - kubenav
    - kubernetes-cli
    - kubernetes-helm
    - kubernetes-kompose
    - kubeval
    - linkerd2
    - minikube
    - tilt
    - velero
  Kubernetes-Desktop: &Kubernetes-Desktop
    - lens
  Linting: &Linting
    - ansible-lint
    - dotenv-linter
    - dprint
    - eslint
    - gitleaks
    - golangci-lint
    - hadolint
    - pre-commit
    - shellcheck
    - shfmt
    - tflint
    - tokei
    - yamllint
  Logging: &Logging
    - fuego
    - papertrail
    - sentry-cli
    - unbuffer
  Media: &Media
    - beets
    # editly NPM package is failing to install on macOS - attempts to compile with node-gyp
    # - editly
    - exiftool
    - ffmpeg
    - imagemagick
    - pandoc
    - sharp
    - spotdl
    - svgo
    - tinypng
    - wkhtmltopdf
    - youtube-dl
  Media-Desktop: &Media-Desktop
    - balenaetcher
    - gimp
    - handbrake
    - inkscape
    - kodi
    - krita
    - lollypop
    - nuclear
    - plex
    - plex-htpc
    - raspberry-pi-imager
    - shotcut
    - shotwell
    - vlc
  Misc-Desktop: &Misc-Desktop
    - _misc-flatpaks
    - cerebro
    - clocker
    - cumulus
    - gnome-tweaks
    - pretzel
    - qlplugins
    - remote-desktop
    - remmina
    - rofi
    - secretive
    - standard-notes
    - stats
    - temps
    - teamviewer
  Misc-Development-Tools: &Misc-Development-Tools
    - ansifilter
    - aqua
    # - asdf # Handled by dotfiles
    # - astronvim
    - automake
    - bfg
    - bundler
    - carthage
    - cmake
    - cocoapods
    - codeclimate
    - dotnet
    - expect
    - fury
    - gradle
    - ideviceinstaller
    - ios-deploy
    - java
    - libimobiledevice
    - rust
    - sdkman
    - snapcraft
    - solidity
    - upx
    - windows-adk
    - windows-admin-center
    - windows-power-toys
  NGINX: &NGINX
    - certbot
    - cfssl
    - gixy
    - mkcert
    - nginx
    # - maas
    - ngxtop
  Network-Enabled: &Network-Enabled
    - cockpit
    - cups
    - lexicon
  Networking: &Networking
    - etcd
    - cloudflared
    - glusterfs
    - mole
    - nebula
    - ngrok
    - ssl-proxy
    - tailscale
    - warp
  Orchestration: &Orchestration
    - nomad
    - pm2
    - waypoint
  PHP: &PHP
    - composer
    - php
  Package-Management: &Package-Management
    # - homebrew
    # - whalebrew
    - zap
  Productivity-Desktop: &Productivity-Desktop
    - libreoffice
    - microsoft-office
    # Deprecated in favor of Google Tasks
    # - microsoft-todo
  Python: &Python
    - poetry
    - python
    - virtualenv
  Recording: &Recording
    - asciinema
    - carbon-now
    - dframe
    - t-rec
  Recording-Desktop: &Recording-Desktop
    - flameshot
    - peek
    - sharex
  Ruby: &Ruby
    - ruby
  SSH: &SSH
    - assh
    - skm
    - ssh-vault
    - sshpass
    - ssh-tarpit
    - sync-ssh-keys
    - teleport
  Security: &Security
    - bitwarden-cli
    - envchain
    - envconsul
    - pony
    - protonvpn-cli
    - skate
    - ssh-vault
    - stubby
    - teller
    - vault
    - yubikey-manager
  Security-Desktop: &Security-Desktop
    - bitwarden
    - mullvad-vpn
    - portmaster
    - protonvpn
    - santa
    - yubikey-authenticator
    - yubikey-manager-qt
  Server: &Server
    - cockpit
    - cups
    - elastic-agent
    - netdata
    - samba
    - sftpgo
    # Headless install needs work since it is run via script
    # - vector
    - wazuh
  Shell-Scripting: &Shell-Scripting
    - shc
    - shdoc
    - shellcheck
    - shfmt
  Social-Networking: &Social-Networking
    - social-analyzer
    - t
  Sys-Admin: &Sys-Admin
    - ctop
    - gtop
    - htop
    - sysbench
    - sysdig
    - sysget
    - upt
    - winrm-cli
    - wireshark-cli
  Sys-Admin-Desktop: &Sys-Admin-Desktop
    - quasar
    - sloth
    - snitch
    - wireshark
  Templates: &Templates
    - confd
    - cookiecutter
    - gomplate
  Terraform: &Terraform
    - terraform
    - tfenv
    - tflint
  Testing: &Testing
    - allure
    - appium
    - molecule
  Transfer: &Transfer
    - aria2
    - croc
    - dat
    - ffsend
    - gdown
    - ots
    - share
  Transfer-Desktop: &Transfer-Desktop
    - dat-desktop
    - filezilla
    - motrix
    - qbittorrent
    - webtorrent
  Utilities: &Utilities
    - nativefier
  Virtualization: &Virtualization
    - kvm
    - lxdc
    # Opens persistent menu icon on GNOME and has issues that sometimes require switching the virt driver
    # - multipass
    - packer
    - vagrant
  Virtualization-Desktop: &Virtualization-Desktop
    - gnome-boxes
    - parallels
    - virtualbox
    - vmware
  Web-Development: &Web-Development
    - angular-cli
    - auto-install
    - browser-sync
    - caniuse
    - cordova
    - deno
    - deta
    - electron
    - emma
    - fastify
    - feathers
    - firebase
    - flutter
    - gfi
    - gulp
    - hey
    - ionic
    - ipfs
    - ipfs-deploy
    - localtunnel
    - mitmproxy
    - muffet
    - ncc
    - nectar
    - nest
    - newman
    - ngrok
    - node-prune
    - np
    - npm-check
    - oclif
    - package-size
    - page-fetch
    - pageres
    - pkg
    - playwright
    - pnpm
    - psi
    - semantic-release
    - serve
    - serverless
    - surge
    - trellis
    - ts2c
    - websocat
    - wordpressify
    - wp-cli
    - wrangler
    - wrk
    - yarn
  Web-Development-Desktop: &Web-Development-Desktop
    - altair
    - betwixt
    - electron-app
    - ipfs-desktop
    - mjml
    - mockoon
    - mqttx
    - postman
    - responsively
    - runjs
  _Basic: &_Basic
    - *CLI
    - *Essentials
  _Basic-Desktop: &_Basic-Desktop
    - *_Basic
    - *Essentials-Desktop
  _Standard: &_Standard
    - *_Basic
    - *Backup
    - *Cloud-Storage
    - bitwarden-cli
  _Standard-Desktop-Filter:
    - discord
    - gitkraken
    - jitsi-meet
    - microsoft-teams
    - microsoft-todo
    - nuclear
    - plex-htpc
    - slack
    - thunderbird
    - yubico-authenticator
    - zoom
  _Standard-Desktop: &_Standard-Desktop
    - *_Basic-Desktop
    - *Backup-Desktop
    - *Communication-Desktop
    - *Media-Desktop
    - *Misc-Desktop
    - *Productivity-Desktop
    - *Recording-Desktop
    - *Virtualization-Desktop
    - bitwarden
    - brave-browser
    - mailspring
    - protonvpn
    - tailscale
    - warp
  _Full: &_Full
    - *_Standard
    - *Android
    - *Ansible
    - *Backup
    - *Browsers
    - *CI
    - *CLI-Extras
    - *Cloud
    - *Cloud-Storage
    - *Crypto
    - *DNS
    - *Data-Manipulation
    - *Database
    - *Docker
    - *E-mail
    - *File-System
    - *Finance
    - *Git
    - *Git-Project-Tools
    - *Go
    - *Home
    - *Kubernetes
    - *Linting
    - *Logging
    - *Media
    - *Misc-Development-Tools
    - *NGINX
    - *Network-Enabled
    - *Networking
    - *Orchestration
    - *PHP
    - *Package-Management
    - *Python
    - *Recording
    - *Ruby
    - *SSH
    - *Security
    - *Server
    - *Shell-Scripting
    - *Social-Networking
    - *Sys-Admin
    - *Terraform
    - *Templates
    - *Testing
    - *Transfer
    - *Utilities
    - *Virtualization
    - *Web-Development
  _Full-Desktop: &_Full-Desktop
    - *_Full
    - *_Standard-Desktop
    - *Android-Desktop
    - *Backup-Desktop
    - *Browsers-Desktop
    - *Communication-Desktop
    - *Crypto-Desktop
    - *Database-Desktop
    - *Development-Tools-Desktop
    - *E-mail-Desktop
    - *Engineering-Desktop
    - *Finance-Desktop
    - *Git-Desktop
    - *Kubernetes-Desktop
    - *Media-Desktop
    - *Misc-Desktop
    - *Productivity-Desktop
    - *Recording-Desktop
    - *Security-Desktop
    - *Sys-Admin-Desktop
    - *Transfer-Desktop
    - *Virtualization-Desktop
    - *Web-Development-Desktop
  __hostname__base-basic-tmpl:
    - *_Basic
    - *_Basic-Desktop
  __hostname__base-standard-tmpl:
    - *_Basic
    - *_Basic-Desktop
    - *Docker
  __hostname__base-full-tmpl:
    - *_Full-Desktop
  __hostname__anon-tmpl:
    - *Anon
  __hostname__crypto-tmpl:
    - *Crypto
    - *Crypto-Desktop
  __hostname__dev-tmpl:
    - *_Full-Desktop
  __hostname__gpg-tmpl: []
  __hostname__kubernetes-tmpl:
    - *Kubernetes
    - *Kubernetes-Desktop
    - *Networking
  __hostname__media-tmpl:
    - *Media
    - *Media-Desktop
  __hostname__office-tmpl:
    - *Communication-Desktop
    - *Productivity-Desktop
  __hostname__personal-tmpl: []
  __hostname__provision-tmpl: []
  __hostname__remote-tmpl:
    - *Networking
    - filezilla
    - remote-desktop
    - teamviewer
  __hostname__swarm-tmpl:
    - *Backup
    - *Docker
    - *Networking
    - swarm
  __hostname__util-tmpl: []
  __hostname__vault-tmpl:
    - onlykey
    - yubikey
  __hostname__vpn-pritunl-tmpl: []
  __hostname__vpn-proton-tmpl:
    - protonvpn
  __hostname__vpn-random-tmpl:
    - vpn
  __hostname__vpn-tailscale-tmpl:
    - tailscale
  __hostname__vpn-warp-tmpl:
    - warp
  __hostname__vpn-tmpl: []
  __hostname__web-tmpl:
    - *Browsers-Desktop
  __hostname__work-tmpl: []
  deprecated:
    - apt-cacher-ng
    - bivac
    - boilr
    - captain
    - consul-template
    - diffsofancy
    - difftastic
    - emplace
    - gvm
    - htop
    - hyper
    - jenv
    - kitty
    - license
    - lpass
    - lsd
    - mackup
    - nordvpn
    - nvm
    - pyenv
    - s3filesystem
    - starship
    - raindrop
    - rear
    - rvm
    - sad
    - supdock
    - termius
    - ulauncher
softwarePlugins:
  vim:
    plugins:
      - https://github.com/dense-analysis/ale.git
      - https://github.com/pearofducks/ansible-vim.git
      - https://github.com/ekalinin/dockerfile.vim.git
      - https://github.com/editorconfig/editorconfig-vim.git
      - https://github.com/junegunn/fzf.git
      - https://github.com/junegunn/fzf.vim.git
      - https://github.com/itchyny/lightline.vim.git
      - https://github.com/scrooloose/nerdtree.git
      - https://github.com/stanangeloff/php.vim.git
      - https://github.com/hdima/python-syntax.git
      - https://github.com/vim-syntastic/syntastic.git
      - https://github.com/vim-airline/vim-airline.git
      - https://github.com/kristijanhusak/vim-carbon-now-sh.git
      - https://github.com/ryanoasis/vim-devicons.git
      - https://github.com/tpope/vim-fugitive.git
      - https://github.com/airblade/vim-gitgutter.git
      - https://github.com/fatih/vim-go.git
      - https://github.com/pangloss/vim-javascript.git
      - https://github.com/mxw/vim-jsx.git
      - https://github.com/plasticboy/vim-markdown.git
      - https://github.com/terryma/vim-multiple-cursors.git
      - https://github.com/prettier/vim-prettier.git
      - https://github.com/tpope/vim-sensible.git
      - https://github.com/tpope/vim-surround.git
      - https://github.com/nanotee/zoxide.vim.git
qubes:
  mirageUrl: https://github.com/mirage/qubes-mirage-firewall/releases/latest/download/mirage-firewall.tar.bz2
  promptKeyboards: false
  provisionVM: provision
  templates:
    # - centos-8
    # - centos-8-minimal
    # - debian-10
    - debian-11
    - debian-11-minimal
    - fedora-32
    - fedora-36
    - fedora-36-minimal
    - fedora-36-xfce
    - fedora-37
    # - gentoo
    # - gentoo-minimal
    # - kali
    - whonix-gw-16
    - whonix-ws-16
  templatesUnofficial:
    - https://qubes.3isec.org/Templates_4.1/qubes-template-archlinux-4.0.6-202204171510.noarch.rpm
    - https://qubes.3isec.org/Templates_4.1/qubes-template-debian-12-4.0.6-202208292254.noarch.rpm
    - https://qubes.3isec.org/Templates_4.1/qubes-template-jammy-4.0.6-202205012228.noarch.rpm
